// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDjF8dpaE52-CIddbE218U7m31XHH6PvE',
    appId: '1:813360799471:web:b377132ac7bd828928c51a',
    messagingSenderId: '813360799471',
    projectId: 'apple-store-b4336',
    authDomain: 'apple-store-b4336.firebaseapp.com',
    storageBucket: 'apple-store-b4336.appspot.com',
    measurementId: 'G-MQBQ5S3MPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1_RGrqelj7Sg3TE2faa6YEPWs1kEcNhg',
    appId: '1:813360799471:android:92ae84249a865d5e28c51a',
    messagingSenderId: '813360799471',
    projectId: 'apple-store-b4336',
    storageBucket: 'apple-store-b4336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcIZjmJumZ5NCwgFrmwam1OwwgVlR22Uc',
    appId: '1:813360799471:ios:85785d7bcfad106428c51a',
    messagingSenderId: '813360799471',
    projectId: 'apple-store-b4336',
    storageBucket: 'apple-store-b4336.appspot.com',
    iosClientId: '813360799471-rrin1pnk9s5aj1ug5r44ij7ddjcm0r0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.appleStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcIZjmJumZ5NCwgFrmwam1OwwgVlR22Uc',
    appId: '1:813360799471:ios:d8d26fa3702fb51528c51a',
    messagingSenderId: '813360799471',
    projectId: 'apple-store-b4336',
    storageBucket: 'apple-store-b4336.appspot.com',
    iosClientId: '813360799471-6jcl099tckcitgt4gcb7iglsk2v8cjss.apps.googleusercontent.com',
    iosBundleId: 'com.example.appleStore.RunnerTests',
  );
}
