// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLzJeXM7bV32uKzeGL9FRDs7E9B1GNybk',
    appId: '1:274865701650:web:c25800a6ffdd237db7a9cb',
    messagingSenderId: '274865701650',
    projectId: 'apple-79ed7',
    authDomain: 'apple-79ed7.firebaseapp.com',
    storageBucket: 'apple-79ed7.appspot.com',
    measurementId: 'G-KRT631BC8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPXZGMeBfHtf6o9PyDIpLMQnFK5Z2nOa8',
    appId: '1:274865701650:android:7d16a8bd51b1e81cb7a9cb',
    messagingSenderId: '274865701650',
    projectId: 'apple-79ed7',
    storageBucket: 'apple-79ed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOkEqQdliD8EMdcMrywpCyhBX2nKQd_Z0',
    appId: '1:274865701650:ios:9577804e65fb7262b7a9cb',
    messagingSenderId: '274865701650',
    projectId: 'apple-79ed7',
    storageBucket: 'apple-79ed7.appspot.com',
    iosClientId: '274865701650-hok7th2aqmqq69l6getptf6q5nlgmoip.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOkEqQdliD8EMdcMrywpCyhBX2nKQd_Z0',
    appId: '1:274865701650:ios:9577804e65fb7262b7a9cb',
    messagingSenderId: '274865701650',
    projectId: 'apple-79ed7',
    storageBucket: 'apple-79ed7.appspot.com',
    iosClientId: '274865701650-hok7th2aqmqq69l6getptf6q5nlgmoip.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineMobile',
  );
}
